SELECT	ContractNo AS ContractNo,
		DunID AS DunID,
		CustomerName AS CustomerName,
		ReceiptVersion AS ReceiptVersion,
		LoanCapital AS LoanCapital,
		ResidualCapital AS ResidualCapital,
		OverdueAmount AS OverdueAmount,
		Capital AS Capital,
		Interest AS Interest,
		ManagementFee AS ManagementFee,
		CapitalInterestLoss AS CapitalInterestLoss,
		ServiceFee AS ServiceFee,
		GuaranteeFee AS GuaranteeFee,
		ServiceFeeLoss AS ServiceFeeLoss,
		Penalty AS Penalty,
		BillFee AS BillFee,
		LoanPeriod AS LoanPeriod,
		RepayPeriod AS RepayPeriod,
		CAST(OverdueDate AS NVARCHAR(50)) AS OverdueDate,
		OverdueDays AS OverdueDays,
		TodayOverdueMark AS TodayOverdueMark,
		BeginningOverdueMark AS BeginningOverdueMark,
		Guarantee AS Guarantee,
		CAST(GuaranteeDate AS NVARCHAR(50)) AS GuaranteeDate,
		GuaranteeAmount AS GuaranteeAmount,
		OutStatus AS OutStatus,
		LitigationStatus AS LitigationStatus,
		CLoanStatus AS CLoanStatus,
		SpecialPolicy AS SpecialPolicy,
		Product AS Product,
		ProductType AS ProductType,
		LendingSide AS LendingSide,
		ServiceSide AS ServiceSide,
		CAST(LoanTime AS NVARCHAR(50)) AS LoanTime,
		SalesChannels AS SalesChannels,
		SigningCity AS SigningCity,
		SigningShop AS SigningShop,
		SalesTeam AS SalesTeam,
		SalesStaff AS SalesStaff,
		CAST(StatisticsDate AS NVARCHAR(50)) AS StatisticsDate
FROM	dbo.OverDueStatic WITH(NOLOCK)
WHERE	1=1
		{0}
ORDER BY ContractNo