SELECT	ContractNo AS [合同编号],
		--DunID AS [催收单号],
		CustomerName AS [客户姓名],
		CustomerProperty AS [客户性质],
		ReceiptVersion AS [借款借据版本],
		LoanCapital AS [贷款金额],
		ResidualCapital AS [剩余本金],
		OverdueAmount AS [逾期金额],
		Capital AS [本金],
		Interest AS [利息],
		ManagementFee AS [管理费],
		CapitalInterestLoss AS [本息扣失],
		ServiceFee AS [服务费],
		GuaranteeFee AS [担保管理费],
		ServiceFeeLoss AS [服务费扣失],
		Penalty AS [罚息],
		BillFee AS [账单费用],
		LoanPeriod AS [贷款期数],
		RepayPeriod AS [贷款期限内已还期数（全部还款）],
		CAST(OverdueDate AS NVARCHAR(50)) AS [逾期日期],
		OverdueDays AS [逾期天数],
		TodayOverdueMark AS [当日逾期标记],
		--BeginningOverdueMark AS [期初逾期标记],
		Guarantee AS [担保],
		CAST(GuaranteeDate AS NVARCHAR(50)) AS [担保日期],
		GuaranteeAmount AS [担保金额],
		OutStatus AS [委外状态],
		LitigationStatus AS [诉讼状态],
		CLoanStatus AS [提前清贷状态],
		SpecialPolicy AS [特殊政策],
		Product AS [贷款产品种类],
		ProductType AS [产品类型],
		LendingSide AS [信托方（放款方）],
		ServiceSide AS [服务方],
		CAST(LoanTime AS NVARCHAR(50)) AS [放款日期],
		SalesChannels AS [销售渠道],
		SigningCity AS [签约地区（城市）],
		SigningShop AS [签约门店],
		SalesTeam AS [团队],
		SalesStaff AS [经办人],
		BusinessID AS [业务号],
		SecondSales AS [二次加贷],
		CustomerID AS [客户号],
		convert(varchar(10),dateadd(dd,-1,StatisticsDate),121) AS [日期]
FROM	dbo.OverDueStatic WITH(NOLOCK)
WHERE	1=1
		{0}
ORDER BY ContractNo
